tap "koekeishiya/formulae"
tap "yqrashawn/goku"

brew "antigen"
brew "atuin"
brew "coreutils"
brew "gnu-sed"
brew "ipython"
brew "mise"
brew "skhd"
brew "starship"
brew "yabai"
brew "yqrashawn/goku/goku"
brew "zsh"

cask "karabiner-elements"
cask "kitty"
