tap "koekeishiya/formulae"
tap "yqrashawn/goku"

brew "antigen"
brew "atuin"
brew "coreutils"
brew "gnu-sed"
brew "ipython"
brew "mise"
brew "skhd"
brew "starship"
brew "yabai"
brew "yqrashawn/goku/goku"
brew "gh"
brew "fzf"
brew "ripgrep"
brew "orbstack"
brew "lazydocker"
brew "tree-sitter"
brew "tree-sitter-cli"

cask "1password-cli"
cask "karabiner-elements"
cask "kitty"

cask "font-jetbrains-mono"
