#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings
yabai -m config layout bsp
yabai -m config window_placement second_child
yabai -m config top_padding 3
yabai -m config bottom_padding 3
yabai -m config left_padding 3
yabai -m config right_padding 3
yabai -m config window_gap 10

## mouse settings

yabai -m config mouse_follows_focus on

# modifier for clicking and dragging with mouse
# yabai -m config mouse_modifier alt

# set modifier + left-click drag to move window
# yabai -m config mouse_action1 move

# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize

# when window is dropped in center of another window, swap them (on edges it will split it)
yabai -m config mouse_drop_action swap


# Disable for specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^CameraController$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^OpenVPN Connect$" manage=off

echo "yabai configuration loaded.."
