# Use starship for the shell prompt
eval "$(starship init zsh)"

source /opt/homebrew/share/antigen/antigen.zsh  # It's getting deprecated

# Load the oh-my-zsh library.
antigen use oh-my-zsh
antigen bundle git
antigen bundle jeffreytse/zsh-vi-mode
antigen apply

# configure vi mode plugin
ZVM_VI_INSERT_ESCAPE_BINDKEY=jk
bindkey -M viins '\e.' insert-last-word

zvm_after_init_commands+=(eval "$(atuin init zsh)")

### aliases

# nvim stuff
export EDITOR=vim
export VISUAL=nvim
alias vi=nvim
alias vig='nvim +Git +only'

# last download
alias ldl='echo "/users/eclbg/downloads/`ls -1 -t /users/eclbg/downloads | head -n 1`"'

# tinybird
alias tinybird_stop="ps -ef | grep 'tinybird_server' | grep -v grep | awk '{print \$2}' | xargs kill -9"
alias tinybird_stop_python="ps -ef | grep 'analytics/.e/bin/python' | grep -v grep | awk '{print \$2}' | xargs kill -9"

# convenience
alias activate='source .venv/bin/activate'
alias act=activate
# not working yet, unfortunately
# function fproc() {
#     res=$(ps -ef | grep '$1' | grep -v grep)
#     echo "$res"
# }
# alias killproc="ps -ef | grep '$1' | grep -v grep | awk '{print \$2}' | xargs kill -9"

# Git
alias gs='git status -uno --ignore-submodules' # Git status without untracked

# Node version manager
eval "$(fnm env --use-on-cd --shell zsh)"

# Add gnu versions of coreutils to the beginning of PATH. These will have no effect unless they've been installed previously with `brew install coreutils
# These include ls, cat, mv, cp...
PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"
# Add gnu-sed to the beginning of PATH
PATH="/opt/homebrew/opt/gnu-sed/libexec/gnubin:$PATH"
# Add gnu patch to PATH
PATH="/opt/homebrew/opt/gpatch/libexec/gnubin:$PATH"
# gnu find
PATH="/opt/homebrew/opt/findutils/libexec/gnubin:$PATH"

# Add more directories to path
PATH="/Users/eclbg/.local/bin:/Users/eclbg/.local/bin/scripts:$PATH"

# 1password completion
eval "$(op completion zsh)"; compdef _op op

# Amp CLI
alias ampide="amp --ide"
alias ampided="amp --ide --dangerously-allow-all --mode smart"
alias ampd="amp --dangerously-allow-all --mode smart"
alias ampidedd="amp --ide --dangerously-allow-all --mode deep"

# Prevent bare directory names from triggering implicit cd.
unsetopt AUTO_CD

# Source machine-specific config if it exists
[ -f ~/.zshrc.local ] && source ~/.zshrc.local
